import React from "react";
import Head from "next/head";
import {
  Text,
  Paper,
  TextInput,
  PasswordInput,
  Button,
  Group,
} from "@mantine/core";
import { Center, Box } from "@mantine/core";
import Link from "next/link";

export default function login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center>
          <Box>
            <Paper shadow="sm" p="xl">
              <h2>Login</h2>
              <TextInput label="Email" placeholder="Email" mt="md" />
              <PasswordInput
                label="Input label"
                placeholder="Input placeholder"
              />
              <Group gap="sm" mt="md">
                <Link href="/login">
                  <Button variant="filled">Login</Button>
                </Link>
                <Link href="/login">
                  <Button variant="filled">Opret</Button>
                </Link>
              </Group>
            </Paper>
          </Box>
        </Center>
      </main>
    </>
  );
}
